### ISSUE TITLE
Inconsistent output with README.md

### ISSUE THREAD

**Issue by koba04** [teppeis/fixclosure#167]
I’ve tried `fixclosure` with a file that is the same as an example in README.md.
But the result was unexpected for me.
Am I missing something?

- Input File

```js
// foo.js (before)
goog.provide('goog.foo.Bar');

goog.require('goog.foo');
goog.require('goog.unused');

goog.foo.Bar = function() {
  goog.foo.baz();
  goog.missing.require();
};
```

- Expected

```
File: foo.js

Provided:
- goog.foo.Bar

Required:
- goog.foo
- goog.unused

Missing Require:
- goog.missing

Unnecessary Require:
- goog.unused

FAIL!

Total: 1 files
Passed: 0 files
Failed: 1 files
```

- Actual

```
File: foo.js

Provided:
- goog.foo.Bar

Required:
- goog.foo
- goog.unused

Unnecessary Require:
- goog.foo
- goog.unused

FAIL!

Total: 1 files
Passed: 0 files
Failed: 1 files
```

**Comment by koba04** [comment]
I can see the expected output by the following command.

```
node bin/fixclosure.js foo.js --namespaces=goog.foo,goog.missing
```

Should I put all namespaces used in scripts as an option?

**Comment by teppeis** [comment]
@koba04 Sorry, the readme is outdated.
In v2, heuristic namespace detection has been removed. In order to detect missing requires, provided namespaces should be given as `--namespaces` or` --depsJs`.

**Comment by koba04** [comment]
Thanks!
