### ISSUE TITLE
node-version

### ISSUE THREAD

**Issue by smaren** [teppeis/fixclosure#272]
We are currently restricted to using a node version <10 since we are using gulp v3. Specifically, we are using node 8. We are currently using our own private fork of fixclosure to validate requires, and in that fork the node version is set to `>=8`, and it seems to work without any issues. Is there a specific reason you have set `"node": ">=10"`? Would you be ok with downgrading to `"node": ">=8"`?

**Comment by teppeis** [comment]
@smaren EOL of Node v8 is 2019-12-31.
https://github.com/nodejs/Release
I don't want to support it because it increases test costs and limits available functions and libraries. Sorry.
