### ISSUE TITLE
Providing @typedef in nested namespace is now disallowed

### ISSUE THREAD

**Issue by gorohash** [teppeis/fixclosure#439]
Since Closure Compiler v20210808, nested `goog.provide` for `@typedef` causes `JSC_TYPEDEF_CHILD_OF_PROVIDE` error.

https://github.com/google/closure-compiler/wiki/Releases#august-8-2021-v20210808
> Ban files with nested goog.provides where a nested goog.provide is used as a `@typedef`. If you see a new `JSC_TYPEDEF_CHILD_OF_PROVIDE` error, the recommended fix is to delete the nested goog.provide (and optionally move to goog.module)

**Comment by teppeis** [comment]
ref. https://github.com/google/closure-compiler/commit/b0e19b8db6d8f027e8dd04efbfa07a95b2645c13
